# Generated by Django 4.2 on 2023-05-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_blog_posts_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
